# Generated by Django 3.2.13 on 2022-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='review',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
